apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: demo
  namespace: us1
  labels:
    prometheus: demo
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  thanos:
    version: v0.14.0
    # Thanos sidecar will be now included!
