apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: demo
  namespace: default
  labels:
    prometheus: demo
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  # Nice, but what about Thanos?
