apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: thanos-receive
  name: thanos-receive
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app: thanos-receive
