apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver-grpc
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
    - name: remote-write
      port: 19291
      protocol: TCP
      targetPort: remote-write
  selector:
    app: thanos-receiver


