apiVersion: v1
kind: Service
metadata:
  name: thanos-ruler
  namespace: default
  labels:
    app: thanos-ruler
spec:
  type: NodePort
  selector:
    app: thanos-ruler
  ports:
  - name: web
    port: 10902
    targetPort: web
    nodePort: 30094
