apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-grpc
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app: thanos-receiver


